"""Add FingerprintEvent table

Revision ID: 6bb572daf1a1
Revises: aafc6298eb34
Create Date: 2025-11-05 03:11:18.315936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb572daf1a1'
down_revision = 'aafc6298eb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprint_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fingerprint_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fingerprint_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fingerprint_events_visitor_id'), ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fingerprint_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fingerprint_events_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_fingerprint_events_request_id'))

    op.drop_table('fingerprint_events')
    # ### end Alembic commands ###
