"""Add reg_visitor_id to User (unique)

Revision ID: 97ec8bc3873e
Revises: 6bb572daf1a1
Create Date: 2025-11-12 03:23:32.393889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ec8bc3873e'
down_revision = '6bb572daf1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_visitor_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_reg_visitor_id'), ['reg_visitor_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reg_visitor_id'))
        batch_op.drop_column('reg_visitor_id')

    # ### end Alembic commands ###
